---
abstract: 'Console Interfaces Module'
author:
  - 'Christophe Guilln <christophe.guillon@st.com'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TestTools-Console
no_index:
  directory:
    - inc
    - t
requires:
  Class::Interface: 0
  Scalar::Util: 0
  Term::ReadLine: 0
  Time::HiRes: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
